#!/usr/bin/env python3
"""Step 5: Assemble final output — merge identifications with polyline coordinates.

Produces:
  - scripts/output/trail_paths.json (consumed by React app)
  - src/data/trailPaths.ts (TypeScript source file)
"""

import json
import sys
from pathlib import Path

from utils.polyline_utils import points_to_percentage, points_to_svg_path

SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent
OUTPUT_DIR = SCRIPT_DIR / "output"
POLYLINES_PATH = OUTPUT_DIR / "extracted_polylines.json"
IDENTIFICATIONS_PATH = OUTPUT_DIR / "trail_identifications.json"
META_PATH = OUTPUT_DIR / "image_meta.json"
OVERRIDES_PATH = SCRIPT_DIR / "manual_overrides.json"

OUTPUT_JSON = OUTPUT_DIR / "trail_paths.json"
OUTPUT_TS = PROJECT_ROOT / "src" / "data" / "trailPaths.ts"


def build_polyline_id_to_trail_id(identifications: dict, polylines_data: dict) -> dict:
    """Build a mapping from polyline_id to trail_id using LLM identifications."""
    mapping = {}

    for peak_id, peak_data in identifications.items():
        if "error" in peak_data:
            continue
        llm_mapping = peak_data.get("mapping", {})
        polyline_ids = peak_data.get("polyline_ids", [])

        for idx_str, trail_id in llm_mapping.items():
            if trail_id == "unknown":
                continue
            idx = int(idx_str)
            if idx < len(polyline_ids):
                mapping[polyline_ids[idx]] = trail_id

    return mapping


def load_manual_overrides() -> dict:
    """Load manual polyline-to-trail overrides."""
    if not OVERRIDES_PATH.exists():
        return {}
    data = json.loads(OVERRIDES_PATH.read_text())
    # Filter out comment keys
    return {k: v for k, v in data.items() if not k.startswith("_")}


def main():
    # Load data
    meta = json.loads(META_PATH.read_text())
    polylines_data = json.loads(POLYLINES_PATH.read_text())
    img_w, img_h = meta["width"], meta["height"]

    accepted = polylines_data["accepted"]
    print(f"Loaded {len(accepted)} accepted polylines")

    # Build identification mapping
    id_mapping = {}
    if IDENTIFICATIONS_PATH.exists():
        identifications = json.loads(IDENTIFICATIONS_PATH.read_text())
        id_mapping = build_polyline_id_to_trail_id(identifications, polylines_data)
        print(f"LLM identifications: {len(id_mapping)} mappings")

    # Apply manual overrides
    overrides = load_manual_overrides()
    id_mapping.update(overrides)
    if overrides:
        print(f"Manual overrides: {len(overrides)} mappings")

    # Build output
    trails_output = {}
    unmatched = []
    duplicate_trails = {}  # trail_id -> list of polyline entries (pick best)

    for polyline in accepted:
        pid = polyline["id"]
        trail_id = id_mapping.get(pid)

        if not trail_id:
            unmatched.append(pid)
            continue

        # Convert to percentage coordinates
        # Points in polyline are [x, y] in pixels
        pct_points = [
            [round(x / img_w * 100, 3), round(y / img_h * 100, 3)]
            for x, y in polyline["points"]
        ]
        svg_path = points_to_svg_path(pct_points)

        entry = {
            "points": pct_points,
            "svgPath": svg_path,
            "color": polyline["color"],
            "polylineId": pid,
        }

        if trail_id in trails_output:
            # Duplicate — keep the one with more points (more detailed path)
            if trail_id not in duplicate_trails:
                duplicate_trails[trail_id] = [trails_output[trail_id]]
            duplicate_trails[trail_id].append(entry)
            if len(pct_points) > len(trails_output[trail_id]["points"]):
                trails_output[trail_id] = entry
        else:
            trails_output[trail_id] = entry

    if duplicate_trails:
        print(f"Resolved {len(duplicate_trails)} duplicate trail matches (kept longest)")

    # Assemble final JSON
    output = {
        "imageWidth": img_w,
        "imageHeight": img_h,
        "trails": {
            tid: {"points": data["points"], "svgPath": data["svgPath"]}
            for tid, data in trails_output.items()
        },
        "unmatched": unmatched,
        "metadata": {
            "dpi": meta["dpi"],
            "matchedCount": len(trails_output),
            "unmatchedCount": len(unmatched),
            "totalPolylines": len(accepted),
        },
    }

    OUTPUT_JSON.write_text(json.dumps(output, indent=2))
    print(f"\nSaved {OUTPUT_JSON}")
    print(f"  Matched: {len(trails_output)} trails")
    print(f"  Unmatched: {len(unmatched)} polylines")

    # Generate TypeScript file
    generate_typescript(output)


def generate_typescript(output: dict):
    """Generate src/data/trailPaths.ts from the output data."""
    trails = output["trails"]

    lines = [
        "// Auto-generated by scripts/05_assemble_output.py",
        "// Do not edit manually — re-run the pipeline to regenerate.",
        "",
        "export interface TrailPath {",
        "  points: [number, number][];",
        "  svgPath: string;",
        "}",
        "",
        "export const trailPaths: Record<string, TrailPath> = {",
    ]

    for trail_id, data in sorted(trails.items()):
        points_str = json.dumps(data["points"])
        svg_escaped = data["svgPath"].replace("\\", "\\\\").replace("'", "\\'")
        lines.append(f"  '{trail_id}': {{")
        lines.append(f"    points: {points_str},")
        lines.append(f"    svgPath: '{svg_escaped}',")
        lines.append(f"  }},")

    lines.append("};")
    lines.append("")

    OUTPUT_TS.write_text("\n".join(lines))
    print(f"Saved {OUTPUT_TS}")


if __name__ == "__main__":
    main()
