// Auto-generated by scripts/05_assemble_output.py
// Do not edit manually — re-run the pipeline to regenerate.

export interface TrailPath {
  points: [number, number][];
  svgPath: string;
}

export const trailPaths: Record<string, TrailPath> = {
};
